import pandas as pd

# Generate three different input variations for CSV testing
data_variations = [
    {
        "timestamp": 1624367008,
        "PCell_RSRP_max": -98.5,
        "PCell_RSRQ_max": -10.2,
        "PCell_RSSI_max": -79.1,
        "PCell_SNR_max": 15.3,
        "PCell_Downlink_Num_RBs": 20,
        "PCell_Downlink_Average_MCS": 5,
        "PCell_Downlink_bandwidth_MHz": 20,
        "PCell_Cell_Identity": 12345,
        "PCell_freq_MHz": 2600,
        "SCell_RSRP_max": -100.2,
        "SCell_RSRQ_max": -11.0,
        "SCell_RSSI_max": -80.5,
        "SCell_SNR_max": 14.8,
        "SCell_Downlink_Num_RBs": 18,
        "SCell_Downlink_Average_MCS": 4,
        "SCell_Downlink_bandwidth_MHz": 15,
        "SCell_Cell_Identity": 54321,
        "SCell_freq_MHz": 2500,
        "operator": 1,
        "Latitude": 48.8566,
        "Longitude": 2.3522,
        "Altitude": 35.0,
        "speed_kmh": 50.0,
        "COG": 0.0,
        "precipIntensity": 0.1,
        "precipProbability": 0.2,
        "temperature": 22.5,
        "apparentTemperature": 23.0,
        "dewPoint": 15.0,
        "humidity": 0.65,
        "pressure": 1015.0,
        "windSpeed": 3.0,
        "cloudCover": 0.5,
        "uvIndex": 5.0,
        "visibility": 10.0,
        "Traffic_Jam_Factor": 3.0,
        "area": 2,
    },
    {
        "timestamp": 1624368010,
        "PCell_RSRP_max": -105.3,
        "PCell_RSRQ_max": -12.5,
        "PCell_RSSI_max": -82.0,
        "PCell_SNR_max": 10.5,
        "PCell_Downlink_Num_RBs": 15,
        "PCell_Downlink_Average_MCS": 6,
        "PCell_Downlink_bandwidth_MHz": 10,
        "PCell_Cell_Identity": 67890,
        "PCell_freq_MHz": 2100,
        "SCell_RSRP_max": -102.5,
        "SCell_RSRQ_max": -13.3,
        "SCell_RSSI_max": -85.2,
        "SCell_SNR_max": 9.2,
        "SCell_Downlink_Num_RBs": 14,
        "SCell_Downlink_Average_MCS": 5,
        "SCell_Downlink_bandwidth_MHz": 20,
        "SCell_Cell_Identity": 98765,
        "SCell_freq_MHz": 2300,
        "operator": 2,
        "Latitude": 34.0522,
        "Longitude": -118.2437,
        "Altitude": 50.0,
        "speed_kmh": 30.0,
        "COG": 10.0,
        "precipIntensity": 0.0,
        "precipProbability": 0.1,
        "temperature": 18.0,
        "apparentTemperature": 19.5,
        "dewPoint": 12.0,
        "humidity": 0.75,
        "pressure": 1012.0,
        "windSpeed": 5.0,
        "cloudCover": 0.3,
        "uvIndex": 3.0,
        "visibility": 8.0,
        "Traffic_Jam_Factor": 5.0,
        "area": 1,
    },
    {
        "timestamp": 1624370020,
        "PCell_RSRP_max": -95.0,
        "PCell_RSRQ_max": -9.0,
        "PCell_RSSI_max": -77.5,
        "PCell_SNR_max": 20.0,
        "PCell_Downlink_Num_RBs": 25,
        "PCell_Downlink_Average_MCS": 7,
        "PCell_Downlink_bandwidth_MHz": 25,
        "PCell_Cell_Identity": 11223,
        "PCell_freq_MHz": 2700,
        "SCell_RSRP_max": -99.0,
        "SCell_RSRQ_max": -10.5,
        "SCell_RSSI_max": -78.0,
        "SCell_SNR_max": 16.0,
        "SCell_Downlink_Num_RBs": 20,
        "SCell_Downlink_Average_MCS": 6,
        "SCell_Downlink_bandwidth_MHz": 18,
        "SCell_Cell_Identity": 55443,
        "SCell_freq_MHz": 2450,
        "operator": 3,
        "Latitude": 51.5074,
        "Longitude": -0.1278,
        "Altitude": 25.0,
        "speed_kmh": 60.0,
        "COG": 5.0,
        "precipIntensity": 0.2,
        "precipProbability": 0.3,
        "temperature": 20.0,
        "apparentTemperature": 21.0,
        "dewPoint": 14.5,
        "humidity": 0.70,
        "pressure": 1018.0,
        "windSpeed": 2.0,
        "cloudCover": 0.6,
        "uvIndex": 4.0,
        "visibility": 12.0,
        "Traffic_Jam_Factor": 2.0,
        "area": 3,
    },
]

# Save each variation as a CSV file
for i, data in enumerate(data_variations):
    df = pd.DataFrame([data])
    df.to_csv(f"test_input_{i+1}.csv", index=False)

print("CSV files generated: test_input_1.csv, test_input_2.csv, test_input_3.csv")
