services:
  fastapi:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
      - elasticsearch
      - mlflow
    restart: always
    ports:
      - "8000:8000"
    environment:
      - IS_DOCKER=true
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2  
    container_name: mlflow_server
    depends_on:
      - db
      - elasticsearch
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow:rw
    user: "0:0"
    environment:
      - BACKEND_STORE_URI=sqlite:///mlflow.db
      - ARTIFACT_ROOT=/mlflow/artifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000

  db:
    image: postgres:14.10  
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: predictions_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2  
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2  
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  pgdata:
  mlflow_data:
